### ISSUE TITLE
To-do's

### ISSUE THREAD

**Issue by eubinecto** [eubinecto/politetune#11]
## 그냥 내가 하고 싶은 것들
- [ ] 두음범칙을 적용하는 거~ (현재 노래를 들어 -> 노래를  듣어요로 바뀌는 중이다. 두음법칙을 적용하면,  노래를 듣어요 -> 노래를 들어요로 바뀌어야 한다).
- [ ] 전체적인 linage를 트래킹하는 거  (그.. 방정식 풀어주는 소프트웨어처럼? 각 단계를 알려줄 수 있는 것이 필요할 듯...)
  -  Before & after를 보여주고 바로 밑에 적용된 규칙을 highlight해서 보여주기
  - 정확히 어떤 어간으로 분리가 되는지, 그 과정도 보여주면 좋을 듯. (self.linage 리스트에 보관하면 될 것 같다)
  1. rules: 어떤 rule이 적용되는지 설명하기. (최종 출력에 when you are speaking to your () and you are speaking in a ( ) environment, then you should use ()) 추가.
  2. honorifics: ban/jon/formal이 어떻게 적용되었는지 설명하기 (before -> after 보여주기)
  3. abbreviations:  어떤 부분이 축약되었는지 설명하기 (before -> after 보여주기)
- [ ] 리드미에 패키지 설치하는 방법 추가하기~ (setup.py 설정. 굳이 pip까지 갈 필요는 없을 것 같다).  
- [ ] 리드미에 이런저런 예시를 보여주는 거 ~  
- [ ] `politetune`보다 더 세련된 이름을 지어주는 거~  (예를 들면 dall-e 같은 것. 문학작품 중에서, 상황에 맞게 존대를 적절하게 하는 그런 캐릭터가 어디 없을까?
- [ ] 각 규칙에 대한 설명을 안내해주는거~ (이 청자에 이 visibility면 왜 1,2,3을 써야하는지?)

## 교수님께서 부탁하신 것들

 - [x] #12
- [x] #14 
- [ ] 한국어와 영어로 예시 정리
