### ISSUE TITLE
청자 리스트 단순화 & formal style 추가

### ISSUE THREAD

**Issue by eubinecto** [eubinecto/politetune#12]
## Why?
지금의 규칙에 좀 더 다양성이 필요하다. 현재는 friend외에는 큰 의미가 없다.
그리고 formal style도 추가를 해야, 사실 더 정확한 높임법을 쓴다고 볼 수 있다. 
<img width="791" alt="image" src="https://user-images.githubusercontent.com/56193069/155665956-beea17bf-32c7-4045-9d6c-8733e642d794.png">

## To-do's
- [x] 일단 브랜치부터 만들고...
- [x] 습니다....는 어떻게 만들지? 종결어미가 아닐텐데?
- [ ] 습니다 축약형 추가하기

**Comment by eubinecto** [comment]
## -습니다 는 어떻게?

일단 탐색을 해보자.

**Comment by eubinecto** [comment]
## 습니다 축약형 추가하기
```yaml
# formal 대응
리습: 립
하습: 합
르이습: 릅

```

저렇게 축약형을 추가하니 다음의 테스트가 잘패스한다:

```python
    def test_formal(self):
        listener, visibility = self.formal
        tuned = self.tuner("나는 내 목표를 향해 달린다", listener, visibility)
        self.assertEqual("저는 제 목표를 향해 달립니다", tuned)
        tuned = self.tuner("나는 공부한다", listener, visibility)
        self.assertEqual("저는 공부합니다", tuned)
        tuned = self.tuner("나는 수영한다", listener, visibility)
        self.assertEqual("저는 수영합니다", tuned)
        tuned = self.tuner("나는 요구한다", listener, visibility)
        self.assertEqual("저는 요구합니다", tuned)
        tuned = self.tuner("나는 목마르다", listener, visibility)
        self.assertEqual("저는 목마릅니다", tuned)
        tuned = self.tuner("나는 내 트로피를 들었다", listener, visibility)
        self.assertEqual("저는 제 트로피를 들었습니다", tuned)


```

**Comment by eubinecto** [comment]
## 문제없이 잘되는듯!

<img width="535" alt="image" src="https://user-images.githubusercontent.com/56193069/155669982-81ff690d-4249-4267-bd3b-b7b073b91df5.png">

테스트도 통과를 하는 것 같으니, 일단 이 이슈는 클로징하겠다!
