### ISSUE TITLE
교수님께서 지적해준 오류 위주로 수정하기

### ISSUE THREAD

**Issue by eubinecto** [eubinecto/politetune#14]
## Why?

다음의 오류를 분석해주셨다:
https://docs.google.com/spreadsheets/d/1bKKMBK_zjkJyftgeRGF4zk2q5mw04hdIDAPlL-GIg_M/edit?usp=sharing

이걸 하나하나씩 수정해나가보자

## To-do's 
- [x] 우선 쉬운 것부터: 하었 -> 했. 이건 축약으로 쉽게 해결이 가능하다.
- [x] 봐었 -> 봤
- [x] 다음은 ㄹ탈락. 이걸 어떻게 해결할지가 고민..
- [x] 토큰 복구 방법 생각해보기

**Comment by eubinecto** [comment]
## 아니 존대만 하면 되는데 왜 국문법을 공부하고 앉아있지?

ㄹ탈락, 두음법칙, 등등...
종결어미만 바꾸는게 내 목표였는데 눈을 떠보니 온갖 문법 교정을 내가 다 하고 있다.

그런데 내가 목표로 했던 것은 이게 아니었다. 난 그냥 어 / 어요 / 습니다로만, 그리고 몇가지 불규칙 변형에만 대응하면 되는 것이었다. 

그런데 문제는.. 대부분의 한국어 형태소 분석기가 그렇게 할수 없도록 디자인 되어 있다는 것. orthography와 lemma를 구분하지 않는게 제일 큰 문제다. 

예를 들어서, 내가 원하는건 다음과 같은 코드다:
    ```python
    sent = "시끄럽게 코고는 소리에 놀라서 난 잠이 깼다."
    tokens = kiwi.tokenize(sent)
    print(tokens)
    orths = [
        sent[token.start: token.start + token.len] if token.len > 0
        else ""
        for token in tokens
    ]
    # 존대
    tuned = [
    "어요" if f"{token.form}+{token.tag}" == "다+EF"
    else orth
    for token, orth in zip(tokens, orths)
    ]
    print(tuned)
    # 반말
    tuned = [
    "습니다" if f"{token.form}+{token.tag}" == "다+EF"
    else orth
    for token, orth in zip(tokens, orths)
    ]
    print(tuned)
    ```

**Comment by eubinecto** [comment]
## 토큰 복구 방법 생각해보기

내 생각에 최악의 상황에서는,  kiwi에 이슈를 남기는 편이 나을수도 있다.

**Comment by eubinecto** [comment]
##  인덱스 교체 방식으로 전환했는데... 

이제 기존에는 걱정하지 않았던 문제를 고민하게 됐다. 

이제는 어간의 받침이 있는 그대로 나온다던지
```
    - 저는 제 목표를 향해 달립니다
E       ?    ^         ^
E       + 저는 저 목표를 향해 달린습니다
```


소유격이 무시된다던지:
```
E       - 저는 제 목표를 향해 달려요
E       ?    ^         ^
E       + 저는 저 목표를 향해 달린어요
E       ?    ^         ^^

```

**Comment by eubinecto** [comment]
## 그렇다면 정말로 모든 문법을 마스터하는 것이 정답인가?
음... 정말로 그래야할까..? 이걸 계속 고민해보아야 한다.

**Comment by eubinecto** [comment]
어쩌면 khaiii가 답일 수도 있겠다!
