### ISSUE TITLE
교수님께서 편하게 작업할 수 있도록, 모든 데이터를 구글 시트로 옮기기 (버전 별 관리가 필요할 것)

### ISSUE THREAD

**Issue by eubinecto** [eubinecto/politetune#4]
## Why?

<img width="557" alt="image" src="https://user-images.githubusercontent.com/56193069/153547707-f3799196-b731-4f3f-9446-43c24c36c9f7.png">

너무 구두로만 부탁드려서 소통에 미스가 났었던 것 같다 ㅠㅠ 편하게 작업하실 수 있도록 도와드리자!

## To-do's
- [x]  rules & description을 구글 시트로 옮기기! 
- [x] description에 몇가지 예시를 추가하기!
- [x] 설명과 함께 메일을 보내드리기!

**Comment by eubinecto** [comment]
## 문제점 발견 
google sheet와 연동하게 되면, csv로 관리하는 것이 더 편할 것 같다. 그렇다고 지금 바로 수정하지는 말고,
나중에 수정하자. csv 파일을 읽어들여서 dictionary로 바꾸는 방법이 있으면 그 방법을 사용하면 될 것 같다.

**Comment by eubinecto** [comment]
## 또다른 문제점 (규칙)

<img width="474" alt="image" src="https://user-images.githubusercontent.com/56193069/153548746-6e0cd102-3a45-4737-82ec-bdb77d73d3e4.png">

규칙을 나열해놓고 보니, visibility를 구분하는 것이 의미있는 경우는 friend밖에 없다. 나머지는 visibility에 관계없이, 반말 아니면 존대다. 그렇다면 friend 하나만을 위해서 visibility를 구분하는 것이 올바른 결정일까? 규칙에 좀 더 다양성을 줄 수 있는 기준은 없는걸까?

**Comment by eubinecto** [comment]
## Rules & Description 추가하기

각각을 따로따로 관리하는 것보단, 그냥 politetune이라는 시트에 각각을  subsheet로 관리하는 편이 더 나을 것 같다. 
그렇게 할 수 있는 시트를 다음 링크에 만들었다:
https://docs.google.com/spreadsheets/d/1SWs_6gR_NH4ROuf4e9FJ44SmEDq7vG3tSAuwt01T11U/edit?usp=sharing

해당 시트에는 다음의 두가지 테이블이 추가되었다:

rules |  descriptions
--- | ---
<img width="426" alt="image" src="https://user-images.githubusercontent.com/56193069/153550019-c0954f8f-dc3b-4ff7-bfcf-73a4efbe1d35.png"> |   <img width="733" alt="image" src="https://user-images.githubusercontent.com/56193069/153550047-34b48077-77b9-4244-929f-53fb1b3160fa.png">

교수님께서는 이번주 안으로 descriptions을 완성해주시면 될 것 같다.

**Comment by eubinecto** [comment]
## Description에 몇가지 예시 추가하기 (piloting)

한국어 honorifics에 대한 literature가 있을까? 단순히 직관을 적어놓는 것보단, 근거가 있는 이유를 적는 편이 나을 것 같은데.

책을 찾아보니 다음과 같은 책이 있다:
<img width="773" alt="image" src="https://user-images.githubusercontent.com/56193069/153550758-08c0512c-3f5c-47cc-b39e-bf1a6777a9f5.png">

한번 읽어보고, visibility와 관련된 내용이 있나 살펴보자.
