### ISSUE TITLE
모든 테스트에 대응할 수 있는 로직을 구현하기 (konlpy -> kiwi 의존성 변경)

### ISSUE THREAD

**Issue by eubinecto** [eubinecto/politetune#5]
## Why?

`konlpy`보다, `kiwi`가 맥락을 고려하여 어간을 추출하는 능력이 더 뛰어나기 때문이다:
```python
from politetune.fetchers import fetch_okt
from kiwipiepy import Kiwi


def main():
    sent = "저는 그 노래를 들어요"
    okt = fetch_okt()
    kiwi = Kiwi()
    print(okt.morphs(sent, stem=True))
    print([token.form for token in kiwi.tokenize(sent)])

    """
    # 듣다라는 어간이 나와야 하는데, okt는 맥락으로부터 듣다를 파악 못함.
    ['저', '는', '그', '노래', '를', '들다']
    # 하지만 kiwi는 맥락으로부터 어간이 듣-이라는 것을 파악할 수 있음.
    ['저', '는', '그', '노래', '를', '듣', '어요']
    """

    sent = "저는 그 상자를 들어요"
    okt = fetch_okt()
    kiwi = Kiwi()
    print(okt.morphs(sent, stem=True))
    print([token.form for token in kiwi.tokenize(sent)])

    """
    ['저', '는', '그', '상자', '를', '들다']
    # 노래를 -> 상자를로 바뀌면, 어간이 들-로 바뀌는 것을 알 수 있음. 이게 더 정확하다.
    ['저', '는', '그', '상자', '를', '들', '어요']
    """

    # 결론 = 그래서 konlpy보단 kiwi를 쓰는 편이 더 정확할 것이다.

if __name__ == '__main__':
    main()

```

이와함께, 사실 konlpy가 m1에서 시원찮게 돌아가는 점이 애초에 맘에 안들었다. 그래서 이참에 jvm의존성을  없애고자, kiwi로  변경을 하고싶기도 하다.  `kiwi`또한 순수 파이썬 라이브러리는 아니지만,  jvm대신 C++로 돌아가며, jvm보단 C++가 m1 호환성이 더 좋다. `kiwi`로 이전하면,
앞으로 이런 찝찝한 오류는 보지 않아도 된다:
```
[0.009s][warning][os,thread] Attempt to protect stack guard pages failed (0x000000016d024000-0x000000016d030000).
[0.009s][warning][os,thread] Attempt to deallocate stack guard pages failed.
['저', '는', '그', '노래', '를', '들다']
['저', '는', '그', '노래', '를', '듣', '어요']
['저', '는', '그', '상자', '를', '들다']
['저', '는', '그', '상자', '를', '들', '어요']
```

정확도도 더 높고,  의존성도 줄어들고. 그래서 kiwi로 이전하고자 한다.

## To-do's
- [x] 대응하고자하는 모든 동사의 활용형에 대한 테스트를 작성해야한다. (pytest 활용하기!)
- [x] kiwi를 활용해서, 모든 테스트에 대응하는 방법을 찾기 
- [x] 간단한 데모 추가하기

**Comment by eubinecto** [comment]
## 대응하고자하는 모든 동사의 활용형에 대한 테스트를 작성하기
### 먼저.. pytest를 활용하더라?
우선, `pytest` 모듈을 설치해주고:
```shell
pip3 install pytest 
```

그리고 예전에 wisdomify에서 했던 것처럼, `tests` 경로를  `setup.cfg`에 지정해주면 된다:
```text
# to ignore unnecessary warnings with pytest
# https://github.com/googleapis/python-api-common-protos/issues/23#issuecomment-756495529
[tool:pytest]
testpaths = tests
filterwarnings =
    ignore:Call to deprecated create function FieldDescriptor
    ignore:Call to deprecated create function Descriptor
    ignore:Call to deprecated create function EnumDescriptor
    ignore:Call to deprecated create function EnumValueDescriptor
    ignore:Call to deprecated create function FileDescriptor
    ignore:Call to deprecated create function OneofDescriptor
```

이렇게 하고나면, 그냥 터미널에 `pytest`만 실행하면 바로 테스트가 실행된다. 편의성 굿!

**Comment by eubinecto** [comment]
## 모든 테스트에 대응하는 방법찾기

**Comment by eubinecto** [comment]
## 모든 테스트에 대응하는 방법찾기 (`Honorifier`)
### 우선 이름부터?

**Comment by eubinecto** [comment]
## 완성!
교수님께서 변화된 규칙을 더 쉽게 확인할 수 있도록 규칙의 적용도 다시 하이라이팅 했다:

<img width="731" alt="image" src="https://user-images.githubusercontent.com/56193069/153813518-b00b1381-a7b4-40b3-901e-07eec3db0c01.png">

tuner의 성능을 확인하기 위해 간단한 데모 스크립트도 만들어보자.
