### ISSUE TITLE
리팩토링 하기

### ISSUE THREAD

**Issue by eubinecto** [eubinecto/politetune#7]
## To-do's?
- ~Tuner의 출력값을 dataclass로 지정 (아니면 튜플로?)하는 거~ (최종 출력을 딕셔너리로 출력하는건 별로...)~
- [x] tuner와 visualiser를 분리하는 거~
- [x] subset 처리하는 거~~
- [x] RULES 데이터 프레임 후처리하는 거~ (main_streamlit.py에서만 후처리를 하는게 영...)
- [x] json 형식을 yaml로 바꾸는 거~

**Comment by eubinecto** [comment]
## Tuner의 출력값을 dataclass (namedtuple)로 지정

`namedtuple`을 어떻게 사용하더라?

**Comment by eubinecto** [comment]
## Rules 데이터프레임 후처리하는 것
이게 문제다. 형식을 데이터 프레임으로 지정하는게 맞나? -> listeners &  visibilities를 바로 접근할 수 있다는 점에서 좋다. 그러면..  abbreviations는 왜 데이터 프레임이 아닌데? 차라리 전부다 dictionary로 지정을 하는게 나을수도 있다.

**Comment by eubinecto** [comment]
## `Tuner`와  `Highlighter` 분리

이 둘을 어떻게 분리해내지? 핵심은 여기에 있다:
```python
subset = pd.IndexSlice[(f"{token.form}+{token.tag}", self.tuner.polite)]
styler = styler.applymap(lambda x: "background-color: purple", subset=subset)
```
어차피 시각화를 할 때 필요한 것은 `subset` 뿐이다. 그리고 `subset`을 만들기 위해서 필요한 것은 (row, column) key pair다.
그렇다면, `Tuner`가 출력해야하는 건... 그냥 subset만 같이 출력하면 된다! 어차피 listener & visibility 조합은 파라미터로 들어오니깐.

그렇게 한번 변경해보자...

우선. `Tuner`의 마지막에 다음과 같이 subset 정보를 등록하도록 만들었다:
```python
        # register any information to be used for post-processing
        self.polite = polite
        self.rule = (listener, visibility)
        self.honorifics = [
            (f"{token.form}+{token.tag}", polite)
            for token in tokens
            if f"{token.form}+{token.tag}" in self.HONORIFICS.keys()
        ]
        self.abbreviations = [
            (key, val)
            for key, val in self.ABBREVIATIONS.items()
            if key in tuned
        ]  # TODO: you may need this later.
        return tuned
```

이 정보는 이후, `Highlighter`에서 다음과 같이 사용된다:
```python
class Highlighter:
    """
    This should work independent of Tuner.
    """
    RULES: pd.DataFrame = pd.DataFrame(fetch_rules()).transpose()
    HONORIFICS: pd.DataFrame = pd.DataFrame(fetch_honorifics()).transpose()

    def __call__(self, rule: Tuple[str, str], honorifics: List[Tuple[str, str]]) -> Tuple[Styler, Styler]:
        """
        :param rule: The rule applied
        :param honorifics: The honorifics applied
        :return: Two stylers
        """
        styler_rule = self.highlight_rule(rule)
        styler_honorifics = self.highlight_honorifics(honorifics)
        # TODO: add a styler for abbreviations
        styler_abbreviations = ...
        return styler_rule, styler_honorifics

    def highlight_rule(self, rule: Tuple[str, str]) -> Styler:
        styler = self.RULES.style
        styler = styler.applymap(lambda x: "background-color: purple", subset=rule)
        return styler

    def highlight_honorifics(self, honorifics: List[Tuple[str, str]]) -> Styler:
        styler = self.HONORIFICS.style
        for honorific in honorifics:
            styler = styler.applymap(lambda x: "background-color: purple", subset=honorific)
        return styler

    def highlight_abbreviations(self) -> Styler:
        raise NotImplementedError

    @property
    def listeners(self):
        return self.RULES.index

    @property
    def visibilities(self):
        return self.RULES.columns


```

**Comment by eubinecto** [comment]
## json ->  yaml로 다시.... 옮기기..

아무래도 json 보다는 yaml이 더 수정하기가 편한 것 같다.

**Comment by eubinecto** [comment]
이제 얼추 요번 이슈는 마무리가 된 것 같다~
